# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: <i class="fas fa-user-tie"></i> CV
    url: uploads/cv_chiba.pdf
    weight: 20
  - name: <i class="fas fa-laptop-code"></i> Research
    url: '#research'
    weight: 30
  - name: <i class="fas fa-book-open"></i> Publications
    url: '#publication'
    weight: 40
  # - name: <i class="fas fa-chalkboard-teacher"></i> Teaching
  #   url: '#teaching'
  #   weight: 40
  - name: <i class="fas fa-atlas"></i> Resources
    url: '#resources'
    weight: 50
  # - name: <i class="fas fa-envelope-square"></i> Contact
  #   url: '#contact'
  #   weight: 60
#  - name: <i class="fas fa-graduation-cap"></i> For Students
#    url: '#students'
#    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
